#!/usr/bin/env bash

echo "Creating .env file"
cat > ./.env <<EOL
APPCENTER_KEYSTORE_PASSWORD=${APPCENTER_KEYSTORE_PASSWORD}
APPCENTER_KEY_ALIAS=${APPCENTER_KEY_ALIAS}
APPCENTER_KEY_PASSWORD=${APPCENTER_KEY_PASSWORD}
EOL